name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-builds:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Test py310
            os: ubuntu-latest
            pyversion: '3.10'
          - name: Test py311
            os: ubuntu-latest
            pyversion: '3.11'
          - name: Test py312
            os: ubuntu-latest
            pyversion: '3.12'
          - name: Test py313
            os: ubuntu-latest
            pyversion: '3.13'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install llvmpipe and lavapipe for offscreen canvas
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y -qq
        sudo apt install -y libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
    - name: Install package and dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Unit tests
      run: |
        pytest -v tests
